CREATE TABLE STUDENTS_2(
	SNUM INTEGER PRIMARY KEY,
	SFAM CHARACTER(20),
	SIMA CHARACTER(20),
	SOTCH CHARACTER(20),
	STIP MONEY DEFAULT 10
);

ALTER TABLE STUDENTS_2
	ADD COURS INTEGER;
	
ALTER TABLE STUDENTS_2
	ADD TELEPHONE CHARACTER(15);
	
ALTER TABLE STUDENTS_2
	DROP COURS;
	
ALTER TABLE STUDENTS_2
	DROP TELEPHONE;
	
CREATE TYPE TELEPHONE AS (
    area_code INTEGER,
    number VARCHAR(20)
);

CREATE DOMAIN TELEPHONE AS VARCHAR(20) NOT NULL;

CREATE INDEX SFAM_IN ON "STUDENTS"("SFAM");

CREATE TABLE "PREDMET_2"(
	"PNUM" SMALLINT,
	"PNAME" CHARACTER(20),
	"TNUM" INTEGER,
	"HOURS" SMALLINT,
	"COURS" SMALLINT
);

CREATE TABLE "TEACHERS_2"(
	"TNUM" INTEGER,
	"TFAM" CHARACTER(20),
	"TIMA" CHARACTER(20),
	"TOTCH" CHARACTER(15),
	"TDATE" DATE
);

CREATE TABLE "USP_2"(
	"UNUM" INTEGER,
	"OCENKA" SMALLINT,
	"UDATE" DATE,
	"SNUM" INTEGER,
	"PNUM" SMALLINT
);

ALTER TABLE "PREDMET_2"
ADD CHECK("COURS" BETWEEN 1 AND 5);

ALTER TABLE "PREDMET_2"
ADD PRIMARY KEY ("PNUM");

ALTER TABLE "TEACHERS_2"
ADD PRIMARY KEY ("TNUM");

ALTER TABLE "STUDENTS_2"
ADD PRIMARY KEY ("SNUM");

ALTER TABLE "USP_2"
ADD PRIMARY KEY ("UNUM");

INSERT INTO "STUDENTS_2"
SELECT *
FROM "STUDENTS" 
WHERE "SFAM" IN 
(SELECT "SFAM"
FROM "STUDENTS"
INNER JOIN "USP" USING ("SNUM")
GROUP BY "SFAM"
HAVING COUNT(*) = COUNT(CASE WHEN "OCENKA" = 5 THEN 1 END));

INSERT INTO "TEACHERS_2"
SELECT * 
FROM "TEACHERS"

INSERT INTO "USP_2"
SELECT * 
FROM "USP"

INSERT INTO "PREDMET_2"
SELECT * 
FROM "PREDMET"

INSERT INTO "STUDENTS_2"
SELECT * FROM "STUDENTS"
EXCEPT 
SELECT * FROM "STUDENTS_2";

ALTER TABLE "USP_2"
ADD CONSTRAINT usp_students_2
FOREIGN KEY ("SNUM")
REFERENCES "STUDENTS_2" ("SNUM")
ON DELETE CASCADE;


ALTER TABLE "USP_2"
ADD CONSTRAINT usp_predmet_2
FOREIGN KEY ("PNUM")
REFERENCES "PREDMET_2" ("PNUM")
ON DELETE CASCADE;


ALTER TABLE "PREDMET_2"
ADD CONSTRAINT predmet_teachers_2
FOREIGN KEY ("TNUM")
REFERENCES "TEACHERS_2" ("TNUM")
ON DELETE CASCADE;

ALTER TABLE "USP_2"
ADD CONSTRAINT CHECK_DATE CHECK("UDATE" < NOW());

ALTER TABLE "PREDMET_2"
ADD CONSTRAINT CHECK_NAME CHECK("PNAME" IN
								('Физика', 'Химия', 'Математика', 'Философия', 'Экономика'));






