.MODEL SMALL

.CODE
PASSWORD DB 'PASSWORD'
PASSWORD_LENGTH EQU $-PASSWORD
START:
   MOV AL, BYTE PTR CS:[0095h]
   SUB AL, 40h
   MOV AH, 0
   PUSH AX
       MOV AL, BYTE PTR CS:[0053h]
       SUB AL, 40h
       MOV AH, 0
       PUSH AX
           MOV AL, BYTE PTR CS:[00BFh]
           SUB AL, 40h
           MOV AH, 0
           PUSH AX
               MOV AL, BYTE PTR CS:[00B0h]
               SUB AL, 40h
               MOV AH, 0
               PUSH AX
                   MOV AL, BYTE PTR CS:[006Dh]
                   SUB AL, 40h
                   MOV AH, 0
                   PUSH AX
                       MOV AL, BYTE PTR CS:[0051h]
                       SUB AL, 40h
                       MOV AH, 0
                       PUSH AX
                           MOV AL, BYTE PTR CS:[0154h]
                           nop
                           nop
                           MOV AH, 0
                           PUSH AX
 MOV AX,@DATA
 MOV DS,AX
 MOV AX,ES:[2CH]
  MOV ES,CX
 MOV ES,AX
 MOV SI,-1
 MOV BX,OFFSET PROGRAM_NAME


SEARCH_01:
 INC SI
 MOV AL,ES:[SI]
 CMP AL,0
 JNE SEARCH_01
 MOV AL,ES:[SI+1]
 CMP AL,1
 JNE SEARCH_01

 ADD SI,2
 INTO

COPY_NAME:
 INC SI
 MOV AL,ES:[SI]
 MOV [BX],AL
 INC BX
 CMP AL,0
 JNE COPY_NAME

 ;MOV ATTEMPTS,3
 ;CALL WRITE_ATTEMPTS

CHECK_PASSWORD:
 MOV DX,OFFSET ATTEMPTS_LEFT
 MOV AH,09H
 INT 21H
 MOV AL,CS:ATTEMPTS
 ADD AL,30H
 INT 29H
 MOV AL,10
 INT 29H
 MOV AL,13
 INT 29H
 MOV DX,OFFSET ENTER_PASSWORD
 MOV AH,09H
 INT 21H
 MOV DX,OFFSET ENTERED_PASSWORD
 MOV AH,0AH
 INT 21H
 MOV AL,10
 INT 29H
 MOV AL,13
 INT 29H

 MOV BX,OFFSET ENTERED_PASSWORD
 MOV AL,[BX+1]
 XOR AH,AH
 POP BX
 CMP AX,BX
 JNE WRONG_PASSWORD
 MOV CX,AX
 MOV SI, OFFSET ENTERED_PASSWORD
 ADD SI, 2

 COMPARE_PASSWORDS:
 POP AX
 MOV AH, [SI]
 CMP AL, AH
 JNE WRONG_PASSWORD
 INC SI
 LOOP COMPARE_PASSWORDS

 MOV CX, 12
 MOV AH, 02h
 MOV DL, 0Dh
 NEWLINE_BEFORE:
 INT 21h
 MOV DL, 0Ah
 INT 21h
 MOV DL, 0Dh
 LOOP NEWLINE_BEFORE

 MOV AH, 09h
 MOV DX, OFFSET CORRECT_PASSWORD
 INT 21h

 MOV CX, 12
 MOV AH, 02h
 MOV DL, 0Dh
 NEWLINE_AFTER:
 INT 21h
 MOV DL, 0Ah
 INT 21h
 MOV DL, 0Dh
 LOOP NEWLINE_AFTER

  MOV AH, 00H
  INT 16H

 MOV AH, 0FH
 INT 10H
 PUSH AX

 MOV AX, 1112H
 INT 10H

 MOV AX, 0B800H
 MOV ES, AX
 MOV DI, 0
 MOV AL, '$'
 MOV AH, 07H
 MOV CX, 4000

 REP STOSW

 MOV AH, 00H
 INT 16H

 POP AX
 MOV AH, 00H
 INT 10H

 MOV AX, 4C00H
 INT 21H

WRONG_PASSWORD:
 MOV AL,CS:ATTEMPTS
 DEC AL
 CMP AL,0
 JE DESTROY
 MOV CS:ATTEMPTS,AL
 CALL WRITE_ATTEMPTS
 JMP CHECK_PASSWORD

DESTROY:
 MOV DX,OFFSET PROGRAM_NAME
 MOV AX,4300H
 INT 21H
 AND CL,11111110B
 MOV AX,4301H
 INT 21H
 MOV AX,3D02H
 INT 21H
 MOV BX,AX
 MOV CX,0
 MOV DX,0
 MOV AX,4202H
 INT 21H
 MOV SI,AX
 MOV ATTEMPTS,0
 MOV CX,0
 MOV DX,0
 MOV AX,4200H
 INT 21H

CLEAR_FILE:
 MOV DX,OFFSET ATTEMPTS
 MOV CX,1
 MOV AH,40H
 INT 21H
 DEC SI
 CMP SI,0
 JE DELETE_FILE
 MOV CX,0
 MOV DX,1
 MOV AX,4201H
 INT 21H
 JMP CLEAR_FILE

DELETE_FILE:
 MOV AH,3EH
 INT 21H
 MOV DX,OFFSET PROGRAM_NAME
 MOV AH,41H
 INT 21H
 MOV DX,OFFSET GOODBYE
 MOV AH,09H
 INT 21H
 MOV AX,4C00H
 INT 21H

WRITE_ATTEMPTS PROC
 MOV DX,OFFSET PROGRAM_NAME
 MOV AX,4300H
 INT 21H
 MOV AX,4301H
 AND CX,11111110B
 INT 21H
 MOV AX,3D02H
 INT 21H
 MOV BX,AX
 MOV CX,0
 MOV DX,0
 MOV AX,4202H
 INT 21H
 MOV CX,0
 SUB AX,17
 MOV DX,AX
 MOV AX,4200H
 INT 21H
 MOV DX,OFFSET ATTEMPTS
 MOV CX,1
 MOV AH,40H
 INT 21H
 MOV AH,3EH
 INT 21H
 RET
WRITE_ATTEMPTS ENDP

.DATA
PROGRAM_NAME DB 256 DUP(?)
ENTER_PASSWORD DB 'Enter password:',10,13,'$'
ENTERED_PASSWORD DB 11,12 DUP(?)
CORRECT_PASSWORD DB 36 DUP(' '),'GIANT!!!',10,13,'$'
GOODBYE DB 'Self-destruction!',10,13,'$'
ATTEMPTS DB 3
ATTEMPTS_LEFT DB 'Attempts left: $'

END START